INSERT INTO paises (fips, fips3, nome) VALUES ('AF', 'AFG', 'Afeganistão');
INSERT INTO paises (fips, fips3, nome) VALUES ('ZA', 'ZAF', 'África do Sul');
INSERT INTO paises (fips, fips3, nome) VALUES ('AX', 'ALA', 'Åland, Ilhas');
INSERT INTO paises (fips, fips3, nome) VALUES ('AL', 'ALB', 'Albânia');
INSERT INTO paises (fips, fips3, nome) VALUES ('DE', 'DEU', 'Alemanha');
INSERT INTO paises (fips, fips3, nome) VALUES ('AD', 'AND', 'Andorra');
INSERT INTO paises (fips, fips3, nome) VALUES ('AO', 'AGO', 'Angola');
INSERT INTO paises (fips, fips3, nome) VALUES ('AI', 'AIA', 'Anguilla');
INSERT INTO paises (fips, fips3, nome) VALUES ('AQ', 'ATA', 'Antárctida');
INSERT INTO paises (fips, fips3, nome) VALUES ('AG', 'ATG', 'Antigua e Barbuda');
INSERT INTO paises (fips, fips3, nome) VALUES ('AN', 'ANT', 'Antilhas Holandesas');
INSERT INTO paises (fips, fips3, nome) VALUES ('SA', 'SAU', 'Arábia Saudita');
INSERT INTO paises (fips, fips3, nome) VALUES ('DZ', 'DZA', 'Argélia');
INSERT INTO paises (fips, fips3, nome) VALUES ('AR', 'ARG', 'Argentina');
INSERT INTO paises (fips, fips3, nome) VALUES ('AM', 'ARM', 'Arménia');
INSERT INTO paises (fips, fips3, nome) VALUES ('AW', 'ABW', 'Aruba');
INSERT INTO paises (fips, fips3, nome) VALUES ('AU', 'AUS', 'Austrália');
INSERT INTO paises (fips, fips3, nome) VALUES ('AT', 'AUT', 'Áustria');
INSERT INTO paises (fips, fips3, nome) VALUES ('AZ', 'AZE', 'Azerbeijão');
INSERT INTO paises (fips, fips3, nome) VALUES ('BS', 'BHS', 'Bahamas');
INSERT INTO paises (fips, fips3, nome) VALUES ('BH', 'BHR', 'Bahrain');
INSERT INTO paises (fips, fips3, nome) VALUES ('BD', 'BGD', 'Bangladesh');
INSERT INTO paises (fips, fips3, nome) VALUES ('BB', 'BRB', 'Barbados');
INSERT INTO paises (fips, fips3, nome) VALUES ('BE', 'BEL', 'Bélgica');
INSERT INTO paises (fips, fips3, nome) VALUES ('BZ', 'BLZ', 'Belize');
INSERT INTO paises (fips, fips3, nome) VALUES ('BJ', 'BEN', 'Benin');
INSERT INTO paises (fips, fips3, nome) VALUES ('BM', 'BMU', 'Bermuda');
INSERT INTO paises (fips, fips3, nome) VALUES ('BY', 'BLR', 'Bielo-Rússia');
INSERT INTO paises (fips, fips3, nome) VALUES ('BO', 'BOL', 'Bolívia');
INSERT INTO paises (fips, fips3, nome) VALUES ('BA', 'BIH', 'Bósnia-Herzegovina');
INSERT INTO paises (fips, fips3, nome) VALUES ('BW', 'BWA', 'Botswana');
INSERT INTO paises (fips, fips3, nome) VALUES ('BV', 'BVT', 'Bouvet, Ilha');
INSERT INTO paises (fips, fips3, nome) VALUES ('BR', 'BRA', 'Brasil');
INSERT INTO paises (fips, fips3, nome) VALUES ('BN', 'BRN', 'Brunei');
INSERT INTO paises (fips, fips3, nome) VALUES ('BG', 'BGR', 'Bulgária');
INSERT INTO paises (fips, fips3, nome) VALUES ('BF', 'BFA', 'Burkina Faso');
INSERT INTO paises (fips, fips3, nome) VALUES ('BI', 'BDI', 'Burundi');
INSERT INTO paises (fips, fips3, nome) VALUES ('BT', 'BTN', 'Butão');
INSERT INTO paises (fips, fips3, nome) VALUES ('CV', 'CPV', 'Cabo Verde');
INSERT INTO paises (fips, fips3, nome) VALUES ('KH', 'KHM', 'Cambodja');
INSERT INTO paises (fips, fips3, nome) VALUES ('CM', 'CMR', 'Camarões');
INSERT INTO paises (fips, fips3, nome) VALUES ('CA', 'CAN', 'Canadá');
INSERT INTO paises (fips, fips3, nome) VALUES ('KY', 'CYM', 'Cayman, Ilhas');
INSERT INTO paises (fips, fips3, nome) VALUES ('KZ', 'KAZ', 'Cazaquistão');
INSERT INTO paises (fips, fips3, nome) VALUES ('CF', 'CAF', 'Centro-africana, República');
INSERT INTO paises (fips, fips3, nome) VALUES ('TD', 'TCD', 'Chade');
INSERT INTO paises (fips, fips3, nome) VALUES ('CZ', 'CZE', 'Checa, República');
INSERT INTO paises (fips, fips3, nome) VALUES ('CL', 'CHL', 'Chile');
INSERT INTO paises (fips, fips3, nome) VALUES ('CN', 'CHN', 'China');
INSERT INTO paises (fips, fips3, nome) VALUES ('CY', 'CYP', 'Chipre');
INSERT INTO paises (fips, fips3, nome) VALUES ('CX', 'CXR', 'Christmas, Ilha');
INSERT INTO paises (fips, fips3, nome) VALUES ('CC', 'CCK', 'Cocos, Ilhas');
INSERT INTO paises (fips, fips3, nome) VALUES ('CO', 'COL', 'Colômbia');
INSERT INTO paises (fips, fips3, nome) VALUES ('KM', 'COM', 'Comores');
INSERT INTO paises (fips, fips3, nome) VALUES ('CG', 'COG', 'Congo, República do');
INSERT INTO paises (fips, fips3, nome) VALUES ('CD', 'COD', 'Congo, República Democrática do (antigo Zaire)');
INSERT INTO paises (fips, fips3, nome) VALUES ('CK', 'COK', 'Cook, Ilhas');
INSERT INTO paises (fips, fips3, nome) VALUES ('KR', 'KOR', 'Coreia do Sul');
INSERT INTO paises (fips, fips3, nome) VALUES ('KP', 'PRK', 'Coreia, República Democrática da (Coreia do Norte)');
INSERT INTO paises (fips, fips3, nome) VALUES ('CI', 'CIV', 'Costa do Marfim');
INSERT INTO paises (fips, fips3, nome) VALUES ('CR', 'CRI', 'Costa Rica');
INSERT INTO paises (fips, fips3, nome) VALUES ('HR', 'HRV', 'Croácia');
INSERT INTO paises (fips, fips3, nome) VALUES ('CU', 'CUB', 'Cuba');
INSERT INTO paises (fips, fips3, nome) VALUES ('DK', 'DNK', 'Dinamarca');
INSERT INTO paises (fips, fips3, nome) VALUES ('DJ', 'DJI', 'Djibouti');
INSERT INTO paises (fips, fips3, nome) VALUES ('DM', 'DMA', 'Dominica');
INSERT INTO paises (fips, fips3, nome) VALUES ('DO', 'DOM', 'Dominicana, República');
INSERT INTO paises (fips, fips3, nome) VALUES ('EG', 'EGY', 'Egipto');
INSERT INTO paises (fips, fips3, nome) VALUES ('SV', 'SLV', 'El Salvador');
INSERT INTO paises (fips, fips3, nome) VALUES ('AE', 'ARE', 'Emiratos Árabes Unidos');
INSERT INTO paises (fips, fips3, nome) VALUES ('EC', 'ECU', 'Equador');
INSERT INTO paises (fips, fips3, nome) VALUES ('ER', 'ERI', 'Eritreia');
INSERT INTO paises (fips, fips3, nome) VALUES ('SK', 'SVK', 'Eslováquia');
INSERT INTO paises (fips, fips3, nome) VALUES ('SI', 'SVN', 'Eslovénia');
INSERT INTO paises (fips, fips3, nome) VALUES ('ES', 'ESP', 'Espanha');
INSERT INTO paises (fips, fips3, nome) VALUES ('US', 'USA', 'Estados Unidos da América');
INSERT INTO paises (fips, fips3, nome) VALUES ('EE', 'EST', 'Estónia');
INSERT INTO paises (fips, fips3, nome) VALUES ('ET', 'ETH', 'Etiópia');
INSERT INTO paises (fips, fips3, nome) VALUES ('FO', 'FRO', 'Faroe, Ilhas');
INSERT INTO paises (fips, fips3, nome) VALUES ('FJ', 'FJI', 'Fiji');
INSERT INTO paises (fips, fips3, nome) VALUES ('PH', 'PHL', 'Filipinas');
INSERT INTO paises (fips, fips3, nome) VALUES ('FI', 'FIN', 'Finlândia');
INSERT INTO paises (fips, fips3, nome) VALUES ('FR', 'FRA', 'França');
INSERT INTO paises (fips, fips3, nome) VALUES ('GA', 'GAB', 'Gabão');
INSERT INTO paises (fips, fips3, nome) VALUES ('GM', 'GMB', 'Gâmbia');
INSERT INTO paises (fips, fips3, nome) VALUES ('GH', 'GHA', 'Gana');
INSERT INTO paises (fips, fips3, nome) VALUES ('GE', 'GEO', 'Geórgia');
INSERT INTO paises (fips, fips3, nome) VALUES ('GS', 'SGS', 'Geórgia do Sul e Sandwich do Sul, Ilhas');
INSERT INTO paises (fips, fips3, nome) VALUES ('GI', 'GIB', 'Gibraltar');
INSERT INTO paises (fips, fips3, nome) VALUES ('GR', 'GRC', 'Grécia');
INSERT INTO paises (fips, fips3, nome) VALUES ('GD', 'GRD', 'Grenada');
INSERT INTO paises (fips, fips3, nome) VALUES ('GL', 'GRL', 'Gronelândia');
INSERT INTO paises (fips, fips3, nome) VALUES ('GP', 'GLP', 'Guadeloupe');
INSERT INTO paises (fips, fips3, nome) VALUES ('GU', 'GUM', 'Guam');
INSERT INTO paises (fips, fips3, nome) VALUES ('GT', 'GTM', 'Guatemala');
INSERT INTO paises (fips, fips3, nome) VALUES ('GG', 'GGY', 'Guernsey');
INSERT INTO paises (fips, fips3, nome) VALUES ('GY', 'GUY', 'Guiana');
INSERT INTO paises (fips, fips3, nome) VALUES ('GF', 'GUF', 'Guiana Francesa');
INSERT INTO paises (fips, fips3, nome) VALUES ('GW', 'GNB', 'Guiné-Bissau');
INSERT INTO paises (fips, fips3, nome) VALUES ('GN', 'GIN', 'Guiné-Conacri');
INSERT INTO paises (fips, fips3, nome) VALUES ('GQ', 'GNQ', 'Guiné Equatorial');
INSERT INTO paises (fips, fips3, nome) VALUES ('HT', 'HTI', 'Haiti');
INSERT INTO paises (fips, fips3, nome) VALUES ('HM', 'HMD', 'Heard e Ilhas McDonald, Ilha');
INSERT INTO paises (fips, fips3, nome) VALUES ('HN', 'HND', 'Honduras');
INSERT INTO paises (fips, fips3, nome) VALUES ('HK', 'HKG', 'Hong Kong');
INSERT INTO paises (fips, fips3, nome) VALUES ('HU', 'HUN', 'Hungria');
INSERT INTO paises (fips, fips3, nome) VALUES ('YE', 'YEM', 'Iémen');
INSERT INTO paises (fips, fips3, nome) VALUES ('IN', 'IND', 'Índia');
INSERT INTO paises (fips, fips3, nome) VALUES ('ID', 'IDN', 'Indonésia');
INSERT INTO paises (fips, fips3, nome) VALUES ('IQ', 'IRQ', 'Iraque');
INSERT INTO paises (fips, fips3, nome) VALUES ('IR', 'IRN', 'Irão');
INSERT INTO paises (fips, fips3, nome) VALUES ('IE', 'IRL', 'Irlanda');
INSERT INTO paises (fips, fips3, nome) VALUES ('IS', 'ISL', 'Islândia');
INSERT INTO paises (fips, fips3, nome) VALUES ('IL', 'ISR', 'Israel');
INSERT INTO paises (fips, fips3, nome) VALUES ('IT', 'ITA', 'Itália');
INSERT INTO paises (fips, fips3, nome) VALUES ('JM', 'JAM', 'Jamaica');
INSERT INTO paises (fips, fips3, nome) VALUES ('JP', 'JPN', 'Japão');
INSERT INTO paises (fips, fips3, nome) VALUES ('JE', 'JEY', 'Jersey');
INSERT INTO paises (fips, fips3, nome) VALUES ('JO', 'JOR', 'Jordânia');
INSERT INTO paises (fips, fips3, nome) VALUES ('KI', 'KIR', 'Kiribati');
INSERT INTO paises (fips, fips3, nome) VALUES ('KW', 'KWT', 'Kuwait');
INSERT INTO paises (fips, fips3, nome) VALUES ('LA', 'LAO', 'Laos');
INSERT INTO paises (fips, fips3, nome) VALUES ('LS', 'LSO', 'Lesoto');
INSERT INTO paises (fips, fips3, nome) VALUES ('LV', 'LVA', 'Letónia');
INSERT INTO paises (fips, fips3, nome) VALUES ('LB', 'LBN', 'Líbano');
INSERT INTO paises (fips, fips3, nome) VALUES ('LR', 'LBR', 'Libéria');
INSERT INTO paises (fips, fips3, nome) VALUES ('LY', 'LBY', 'Líbia');
INSERT INTO paises (fips, fips3, nome) VALUES ('LI', 'LIE', 'Liechtenstein');
INSERT INTO paises (fips, fips3, nome) VALUES ('LT', 'LTU', 'Lituânia');
INSERT INTO paises (fips, fips3, nome) VALUES ('LU', 'LUX', 'Luxemburgo');
INSERT INTO paises (fips, fips3, nome) VALUES ('MO', 'MAC', 'Macau');
INSERT INTO paises (fips, fips3, nome) VALUES ('MK', 'MKD', 'Macedónia, República da');
INSERT INTO paises (fips, fips3, nome) VALUES ('MG', 'MDG', 'Madagáscar');
INSERT INTO paises (fips, fips3, nome) VALUES ('MY', 'MYS', 'Malásia');
INSERT INTO paises (fips, fips3, nome) VALUES ('MW', 'MWI', 'Malawi');
INSERT INTO paises (fips, fips3, nome) VALUES ('MV', 'MDV', 'Maldivas');
INSERT INTO paises (fips, fips3, nome) VALUES ('ML', 'MLI', 'Mali');
INSERT INTO paises (fips, fips3, nome) VALUES ('MT', 'MLT', 'Malta');
INSERT INTO paises (fips, fips3, nome) VALUES ('FK', 'FLK', 'Malvinas, Ilhas (Falkland)');
INSERT INTO paises (fips, fips3, nome) VALUES ('IM', 'IMN', 'Man, Ilha de');
INSERT INTO paises (fips, fips3, nome) VALUES ('MP', 'MNP', 'Marianas Setentrionais');
INSERT INTO paises (fips, fips3, nome) VALUES ('MA', 'MAR', 'Marrocos');
INSERT INTO paises (fips, fips3, nome) VALUES ('MH', 'MHL', 'Marshall, Ilhas');
INSERT INTO paises (fips, fips3, nome) VALUES ('MQ', 'MTQ', 'Martinica');
INSERT INTO paises (fips, fips3, nome) VALUES ('MU', 'MUS', 'Maurícia');
INSERT INTO paises (fips, fips3, nome) VALUES ('MR', 'MRT', 'Mauritânia');
INSERT INTO paises (fips, fips3, nome) VALUES ('YT', 'MYT', 'Mayotte');
INSERT INTO paises (fips, fips3, nome) VALUES ('UM', 'UMI', 'Menores Distantes dos Estados Unidos, Ilhas');
INSERT INTO paises (fips, fips3, nome) VALUES ('MX', 'MEX', 'México');
INSERT INTO paises (fips, fips3, nome) VALUES ('MM', 'MMR', 'Myanmar (antiga Birmânia)');
INSERT INTO paises (fips, fips3, nome) VALUES ('FM', 'FSM', 'Micronésia, Estados Federados da');
INSERT INTO paises (fips, fips3, nome) VALUES ('MZ', 'MOZ', 'Moçambique');
INSERT INTO paises (fips, fips3, nome) VALUES ('MD', 'MDA', 'Moldávia');
INSERT INTO paises (fips, fips3, nome) VALUES ('MC', 'MCO', 'Mónaco');
INSERT INTO paises (fips, fips3, nome) VALUES ('MN', 'MNG', 'Mongólia');
INSERT INTO paises (fips, fips3, nome) VALUES ('ME', 'MNE', 'Montenegro');
INSERT INTO paises (fips, fips3, nome) VALUES ('MS', 'MSR', 'Montserrat');
INSERT INTO paises (fips, fips3, nome) VALUES ('NA', 'NAM', 'Namíbia');
INSERT INTO paises (fips, fips3, nome) VALUES ('NR', 'NRU', 'Nauru');
INSERT INTO paises (fips, fips3, nome) VALUES ('NP', 'NPL', 'Nepal');
INSERT INTO paises (fips, fips3, nome) VALUES ('NI', 'NIC', 'Nicarágua');
INSERT INTO paises (fips, fips3, nome) VALUES ('NE', 'NER', 'Níger');
INSERT INTO paises (fips, fips3, nome) VALUES ('NG', 'NGA', 'Nigéria');
INSERT INTO paises (fips, fips3, nome) VALUES ('NU', 'NIU', 'Niue');
INSERT INTO paises (fips, fips3, nome) VALUES ('NF', 'NFK', 'Norfolk, Ilha');
INSERT INTO paises (fips, fips3, nome) VALUES ('NO', 'NOR', 'Noruega');
INSERT INTO paises (fips, fips3, nome) VALUES ('NC', 'NCL', 'Nova Caledónia');
INSERT INTO paises (fips, fips3, nome) VALUES ('NZ', 'NZL', 'Nova Zelândia (Aotearoa)');
INSERT INTO paises (fips, fips3, nome) VALUES ('OM', 'OMN', 'Oman');
INSERT INTO paises (fips, fips3, nome) VALUES ('NL', 'NLD', 'Países Baixos (Holanda)');
INSERT INTO paises (fips, fips3, nome) VALUES ('PW', 'PLW', 'Palau');
INSERT INTO paises (fips, fips3, nome) VALUES ('PS', 'PSE', 'Palestina');
INSERT INTO paises (fips, fips3, nome) VALUES ('PA', 'PAN', 'Panamá');
INSERT INTO paises (fips, fips3, nome) VALUES ('PG', 'PNG', 'Papua-Nova Guiné');
INSERT INTO paises (fips, fips3, nome) VALUES ('PK', 'PAK', 'Paquistão');
INSERT INTO paises (fips, fips3, nome) VALUES ('PY', 'PRY', 'Paraguai');
INSERT INTO paises (fips, fips3, nome) VALUES ('PE', 'PER', 'Peru');
INSERT INTO paises (fips, fips3, nome) VALUES ('PN', 'PCN', 'Pitcairn');
INSERT INTO paises (fips, fips3, nome) VALUES ('PF', 'PYF', 'Polinésia Francesa');
INSERT INTO paises (fips, fips3, nome) VALUES ('PL', 'POL', 'Polónia');
INSERT INTO paises (fips, fips3, nome) VALUES ('PR', 'PRI', 'Porto Rico');
INSERT INTO paises (fips, fips3, nome) VALUES ('PT', 'PRT', 'Portugal');
INSERT INTO paises (fips, fips3, nome) VALUES ('QA', 'QAT', 'Qatar');
INSERT INTO paises (fips, fips3, nome) VALUES ('KE', 'KEN', 'Quénia');
INSERT INTO paises (fips, fips3, nome) VALUES ('KG', 'KGZ', 'Quirguistão');
INSERT INTO paises (fips, fips3, nome) VALUES ('GB', 'GBR', 'Reino Unido da Grã-Bretanha e Irlanda do Norte');
INSERT INTO paises (fips, fips3, nome) VALUES ('RE', 'REU', 'Reunião');
INSERT INTO paises (fips, fips3, nome) VALUES ('RO', 'ROU', 'Roménia');
INSERT INTO paises (fips, fips3, nome) VALUES ('RW', 'RWA', 'Ruanda');
INSERT INTO paises (fips, fips3, nome) VALUES ('RU', 'RUS', 'Rússia');
INSERT INTO paises (fips, fips3, nome) VALUES ('EH', 'ESH', 'Saara Ocidental');
INSERT INTO paises (fips, fips3, nome) VALUES ('AS', 'ASM', 'Samoa Americana');
INSERT INTO paises (fips, fips3, nome) VALUES ('WS', 'WSM', 'Samoa (Samoa Ocidental)');
INSERT INTO paises (fips, fips3, nome) VALUES ('PM', 'SPM', 'Saint Pierre et Miquelon');
INSERT INTO paises (fips, fips3, nome) VALUES ('SB', 'SLB', 'Salomão, Ilhas');
INSERT INTO paises (fips, fips3, nome) VALUES ('KN', 'KNA', 'São Cristóvão e Névis (Saint Kitts e Nevis)');
INSERT INTO paises (fips, fips3, nome) VALUES ('SM', 'SMR', 'San Marino');
INSERT INTO paises (fips, fips3, nome) VALUES ('ST', 'STP', 'São Tomé e Príncipe');
INSERT INTO paises (fips, fips3, nome) VALUES ('VC', 'VCT', 'São Vicente e Granadinas');
INSERT INTO paises (fips, fips3, nome) VALUES ('SH', 'SHN', 'Santa Helena');
INSERT INTO paises (fips, fips3, nome) VALUES ('LC', 'LCA', 'Santa Lúcia');
INSERT INTO paises (fips, fips3, nome) VALUES ('SN', 'SEN', 'Senegal');
INSERT INTO paises (fips, fips3, nome) VALUES ('SL', 'SLE', 'Serra Leoa');
INSERT INTO paises (fips, fips3, nome) VALUES ('RS', 'SRB', 'Sérvia');
INSERT INTO paises (fips, fips3, nome) VALUES ('SC', 'SYC', 'Seychelles');
INSERT INTO paises (fips, fips3, nome) VALUES ('SG', 'SGP', 'Singapura');
INSERT INTO paises (fips, fips3, nome) VALUES ('SY', 'SYR', 'Síria');
INSERT INTO paises (fips, fips3, nome) VALUES ('SO', 'SOM', 'Somália');
INSERT INTO paises (fips, fips3, nome) VALUES ('LK', 'LKA', 'Sri Lanka');
INSERT INTO paises (fips, fips3, nome) VALUES ('SZ', 'SWZ', 'Suazilândia');
INSERT INTO paises (fips, fips3, nome) VALUES ('SD', 'SDN', 'Sudão');
INSERT INTO paises (fips, fips3, nome) VALUES ('SE', 'SWE', 'Suécia');
INSERT INTO paises (fips, fips3, nome) VALUES ('CH', 'CHE', 'Suíça');
INSERT INTO paises (fips, fips3, nome) VALUES ('SR', 'SUR', 'Suriname');
INSERT INTO paises (fips, fips3, nome) VALUES ('SJ', 'SJM', 'Svalbard e Jan Mayen');
INSERT INTO paises (fips, fips3, nome) VALUES ('TH', 'THA', 'Tailândia');
INSERT INTO paises (fips, fips3, nome) VALUES ('TW', 'TWN', 'Taiwan');
INSERT INTO paises (fips, fips3, nome) VALUES ('TJ', 'TJK', 'Tajiquistão');
INSERT INTO paises (fips, fips3, nome) VALUES ('TZ', 'TZA', 'Tanzânia');
INSERT INTO paises (fips, fips3, nome) VALUES ('TF', 'ATF', 'Terras Austrais e Antárticas Francesas (TAAF)');
INSERT INTO paises (fips, fips3, nome) VALUES ('IO', 'IOT', 'Território Britânico do Oceano Índico');
INSERT INTO paises (fips, fips3, nome) VALUES ('TL', 'TLS', 'Timor-Leste');
INSERT INTO paises (fips, fips3, nome) VALUES ('TG', 'TGO', 'Togo');
INSERT INTO paises (fips, fips3, nome) VALUES ('TK', 'TKL', 'Toquelau');
INSERT INTO paises (fips, fips3, nome) VALUES ('TO', 'TON', 'Tonga');
INSERT INTO paises (fips, fips3, nome) VALUES ('TT', 'TTO', 'Trindade e Tobago');
INSERT INTO paises (fips, fips3, nome) VALUES ('TN', 'TUN', 'Tunísia');
INSERT INTO paises (fips, fips3, nome) VALUES ('TC', 'TCA', 'Turks e Caicos');
INSERT INTO paises (fips, fips3, nome) VALUES ('TM', 'TKM', 'Turquemenistão');
INSERT INTO paises (fips, fips3, nome) VALUES ('TR', 'TUR', 'Turquia');
INSERT INTO paises (fips, fips3, nome) VALUES ('TV', 'TUV', 'Tuvalu');
INSERT INTO paises (fips, fips3, nome) VALUES ('UA', 'UKR', 'Ucrânia');
INSERT INTO paises (fips, fips3, nome) VALUES ('UG', 'UGA', 'Uganda');
INSERT INTO paises (fips, fips3, nome) VALUES ('UY', 'URY', 'Uruguai');
INSERT INTO paises (fips, fips3, nome) VALUES ('UZ', 'UZB', 'Usbequistão');
INSERT INTO paises (fips, fips3, nome) VALUES ('VU', 'VUT', 'Vanuatu');
INSERT INTO paises (fips, fips3, nome) VALUES ('VA', 'VAT', 'Vaticano');
INSERT INTO paises (fips, fips3, nome) VALUES ('VE', 'VEN', 'Venezuela');
INSERT INTO paises (fips, fips3, nome) VALUES ('VN', 'VNM', 'Vietname');
INSERT INTO paises (fips, fips3, nome) VALUES ('VI', 'VIR', 'Virgens Americanas, Ilhas');
INSERT INTO paises (fips, fips3, nome) VALUES ('VG', 'VGB', 'Virgens Britânicas, Ilhas');
INSERT INTO paises (fips, fips3, nome) VALUES ('WF', 'WLF', 'Wallis e Futuna');
INSERT INTO paises (fips, fips3, nome) VALUES ('ZM', 'ZMB', 'Zâmbia');
INSERT INTO paises (fips, fips3, nome) VALUES ('ZW', 'ZWE', 'Zimbabwe');