INSERT INTO estados (nome, uf, idPais) VALUES ('Acre', 'AC', 33);
INSERT INTO estados (nome, uf, idPais) VALUES ('Alagoas', 'AL', 33);
INSERT INTO estados (nome, uf, idPais) VALUES ('Amazonas', 'AM', 33);
INSERT INTO estados (nome, uf, idPais) VALUES ('Amapá', 'AP', 33);
INSERT INTO estados (nome, uf, idPais) VALUES ('Bahia', 'BA', 33);
INSERT INTO estados (nome, uf, idPais) VALUES ('Ceará', 'CE', 33);
INSERT INTO estados (nome, uf, idPais) VALUES ('Distrito Federal', 'DF', 33);
INSERT INTO estados (nome, uf, idPais) VALUES ('Espírito Santo', 'ES', 33);
INSERT INTO estados (nome, uf, idPais) VALUES ('Goiás', 'GO', 33);
INSERT INTO estados (nome, uf, idPais) VALUES ('Maranhão', 'MA', 33);
INSERT INTO estados (nome, uf, idPais) VALUES ('Minas Gerais', 'MG', 33);
INSERT INTO estados (nome, uf, idPais) VALUES ('Mato Grosso do Sul', 'MS', 33);
INSERT INTO estados (nome, uf, idPais) VALUES ('Mato Grosso', 'MT', 33);
INSERT INTO estados (nome, uf, idPais) VALUES ('Pará', 'PA', 33);
INSERT INTO estados (nome, uf, idPais) VALUES ('Paraíba', 'PB', 33);
INSERT INTO estados (nome, uf, idPais) VALUES ('Pernambuco', 'PE', 33);
INSERT INTO estados (nome, uf, idPais) VALUES ('Piauí', 'PI', 33);
INSERT INTO estados (nome, uf, idPais) VALUES ('Paraná', 'PR', 33);
INSERT INTO estados (nome, uf, idPais) VALUES ('Rio de Janeiro', 'RJ', 33);
INSERT INTO estados (nome, uf, idPais) VALUES ('Rio Grande do Norte', 'RN', 33);
INSERT INTO estados (nome, uf, idPais) VALUES ('Rondônia', 'RO', 33);
INSERT INTO estados (nome, uf, idPais) VALUES ('Roraima', 'RR', 33);
INSERT INTO estados (nome, uf, idPais) VALUES ('Rio Grande do Sul', 'RS', 33);
INSERT INTO estados (nome, uf, idPais) VALUES ('Santa Catarina', 'SC', 33);
INSERT INTO estados (nome, uf, idPais) VALUES ('Sergipe', 'SE', 33);
INSERT INTO estados (nome, uf, idPais) VALUES ('São Paulo', 'SP', 33);
INSERT INTO estados (nome, uf, idPais) VALUES ('Tocantins', 'TO', 33);